/* Shared Tailwind theme + base CSS.
 *
 * The Material palette (primary / on-surface / surface-container / ...) was
 * originally inlined in index.html only, so every other page rendered the
 * shared navbar UNSTYLED - the classes simply did not exist there.
 *
 * Every page now loads the Tailwind CDN followed by this file, so the
 * navbar looks identical everywhere.
 */
tailwind.config={darkMode:"class",theme:{extend:{"colors":{"on-secondary-container":"#007233","on-secondary-fixed-variant":"#005323","on-surface-variant":"#57423b","on-secondary":"#ffffff","on-error-container":"#93000a","surface-bright":"#fff8f6","on-surface":"#1e1b1a","surface-dim":"#e1d8d6","primary-container":"#c15326","error-container":"#ffdad6","on-background":"#1e1b1a","error":"#ba1a1a","on-primary-fixed":"#380d00","surface":"#fff8f6","surface-container-high":"#efe6e4","surface-variant":"#e9e1df","secondary-container":"#92f5a4","surface-container-highest":"#e9e1df","on-error":"#ffffff","on-primary-fixed-variant":"#812900","on-tertiary-fixed":"#001d31","on-primary-container":"#fffbff","inverse-primary":"#ffb59a","primary":"#a03b0e","outline":"#8b7269","surface-container-low":"#fbf2f0","secondary":"#006d30","secondary-fixed-dim":"#79db8d","surface-tint":"#a33e11","primary-fixed":"#ffdbcf","tertiary":"#006194","surface-container":"#f5ecea","inverse-on-surface":"#f8efed","surface-container-lowest":"#ffffff","on-primary":"#ffffff","secondary-fixed":"#95f8a7","background":"#fff8f6","tertiary-fixed-dim":"#93ccff","tertiary-container":"#007bb9","outline-variant":"#dec0b6","inverse-surface":"#342f2e","on-tertiary-container":"#fdfcff","on-tertiary":"#ffffff","on-tertiary-fixed-variant":"#004b73","on-secondary-fixed":"#00210a","primary-fixed-dim":"#ffb59a","tertiary-fixed":"#cce5ff"},"borderRadius":{"DEFAULT":"1rem","lg":"2rem","xl":"3rem","full":"9999px"},"spacing":{"space-xs":"0.375rem","space-lg":"1.5rem","space-xl":"2rem","13":"3.25rem","gutter":"1rem","space-sm":"0.5rem","margin":"1rem","space-md":"1rem","space-xs":"0.25rem","space-lg":"1.5rem","gutter-desktop":"1.5rem","margin-desktop":"2rem","space-xl":"2rem"},"fontFamily":{"headline-sm":["Plus Jakarta Sans"],"label-sm":["Inter"],"headline-md":["Plus Jakarta Sans"],"body-sm":["Plus Jakarta Sans"],"label-md":["Inter"],"stat-counter":["Inter"],"body-md":["Plus Jakarta Sans"],"headline-lg-mobile":["Plus Jakarta Sans"],"body-lg":["Plus Jakarta Sans"],"label-lg":["Inter"],"headline-lg":["Plus Jakarta Sans"]},"fontSize":{"headline-sm":["18px",{"lineHeight":"24px","fontWeight":"600"}],"label-sm":["11px",{"lineHeight":"14px","letterSpacing":"0.04em","fontWeight":"600"}],"headline-md":["22px",{"lineHeight":"28px","fontWeight":"600"}],"body-sm":["13px",{"lineHeight":"18px","fontWeight":"400"}],"label-md":["12px",{"lineHeight":"16px","letterSpacing":"0.02em","fontWeight":"600"}],"stat-counter":["15px",{"lineHeight":"18px","fontWeight":"700"}],"body-md":["14px",{"lineHeight":"20px","fontWeight":"400"}],"headline-lg-mobile":["26px",{"lineHeight":"32px","fontWeight":"700"}],"body-lg":["16px",{"lineHeight":"24px","fontWeight":"400"}],"label-lg":["14px",{"lineHeight":"20px","letterSpacing":"0.01em","fontWeight":"600"}],"headline-lg":["32px",{"lineHeight":"40px","fontWeight":"700"}]}}}};
